[package]
name = "metaitus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
efficax-utils = { path = "../efficax-utils" }
cgmath = "0.18.0"